---
- name: develop group
  group: name=develop gid=200 state=present
  tags: devteam

- name: devteam users
  user: name={{ item.name }} groups={{ devteam_groups }} shell={{ item.shell }} state=present
  tags: devteam
  with_items: "{{devteam_users}}"

- name: devteam ssh keys
  authorized_key: user={{ item.0.name }} key="{{ item.1 }}"
  tags: devteam
  with_subelements:
    - "{{devteam_users}}"
    - ssh_keys

- name: devteam dot files
  copy:
    src: "{{ item.0.name }}/{{ item.1 }}"
    dest: /home/{{ item.0.name }}/.{{ item.1 }}
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
  with_subelements:
    - "{{devteam_users}}"
    - dot_files
  tags: devteam

- name: devteam sudo
  template:
    src: sudoer.j2
    dest: /etc/sudoers.d/{{ item.name }}
    owner: root
    mode: "0440"
  tags: devteam
  with_items: "{{devteam_users}}"
  when: "item.sudo|d(False) == True"


